apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deployment.yml
- frontend/service.yml
- backend/deployment.yml
- backend/service.yml
- ingress.yml
images:
- name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/backend
  newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/backend
  newTag: e26e55726f3d51170f1d9e2be7579b21f4b5b4f4
- name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/frontend
  newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/frontend
  newTag: v1.0
