apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-na-nuvem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kenerry-serain/minicurso-devops-e-aws-dia-07-gitops
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true